config/routes.rb
Rails.application.routes.draw do
  resources :matches
  namespace :admin do
    resources :users
    resources :games
    resources :news
    resources :reddits
    resources :youtubes
    resources :guides
    resources :streamers
    resources :headlines
    resources :matches
    root to: "users#index"
  end

 devise_for :users
 root to: "home#index"
 get '/dota2', to: "dota#index"
 get '/csgo', to: "csgo#index"
 get '/dashboard', to: "dashboard#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :news, dependent: :destroy
  has_many :guides, dependent: :destroy
  has_many :reddits, dependent: :destroy
  has_many :streamers, dependent: :destroy
  has_many :youtubes, dependent: :destroy
  has_many :headlines, dependent: :destroy
  has_many :matches, dependent: :destroy
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :game, dependent: :destroy
end

app/models/headline.rb
class Headline < ActiveRecord::Base
  belongs_to :game, dependent: :destroy
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :game
  after_initialize :init

  def init
    self.status ||= "upcoming"
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :game
end

app/models/reddit.rb
class Reddit < ActiveRecord::Base
  belongs_to :game, dependent: :destroy
end

app/models/streamer.rb
class Streamer < ActiveRecord::Base
  belongs_to :game, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :username, presence: true,
                         format: { with: /\A[a-zA-Z0-9]+\Z/, message: 'can only contain letters and numbers' },
                         length: { in: 4..16, message: 'must contain between 4 and 16 characters' },
                         uniqueness: true
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    def is_admin?
      self.role.eql?("Admin")
    end
end

app/models/youtube.rb
class Youtube < ActiveRecord::Base
  belongs_to :game, dependent: :destroy
end

app/controllers/admin/matches_controller.rb
module Admin
  class MatchesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Match.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Match.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/csgo_controller.rb
class CsgoController < ApplicationController
    def index
        @news = Game.find_by(:name => 'Counterstrike Global Offensive').news.last(5)
        @reddit = Game.find_by(:name => 'Counterstrike Global Offensive').reddits.last(5)
        @streamers = Game.find_by(:name => 'Counterstrike Global Offensive').streamers.last(6)
        @youtube = Game.find_by(:name => 'Counterstrike Global Offensive').youtubes.last(3).reverse
        @guides = Game.find_by(:name => 'Counterstrike Global Offensive').guides.last(5).reverse
        @headlines = Game.find_by(:name => 'Counterstrike Global Offensive').headlines.last(4).reverse
    end
end

app/controllers/dota_controller.rb
class DotaController < ApplicationController
  def index
    @news = Game.find_by(:name => 'Dota 2').news.last(5)
    @reddit = Game.find_by(:name => 'Dota 2').reddits.last(5)
    @streamers = Game.find_by(:name => 'Dota 2').streamers.last(6)
    @youtube = Game.find_by(:name => 'Dota 2').youtubes.last(3).reverse
    @guides = Game.find_by(:name => 'Dota 2').guides.last(5).reverse
    @headlines = Game.find_by(:name => 'Dota 2').headlines.last(4).reverse
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @reddit = Game.find_by(:name => 'Gaming').reddits.last(5)
    @streamers = Game.find_by(:name => 'Gaming').streamers.last(6)
    @headlines = Headline.last(5).reverse
    matches = Match.all
    @live_matches, @upcoming_matches, @completed_matches = [], [], []
    matches.each do |match|
      case match.status
      when "live"
        @live_matches << match
      when "upcoming"
        @upcoming_matches << match
      when "completed"
        @completed_matches << match
      else
        @upcoming_matches << match
      end
    end
    @live_matches.sort! {|a,b| a.time <=> b.time} if @live_matches.size > 1
    @upcoming_matches.sort! {|a,b| a.time <=> b.time} if @upcoming_matches.size > 1
    @completed_matches.sort! {|a,b| b.time <=> a.time} if @completed_matches.size > 1
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:team1, :team1_score, :team2, :team2_score, :game_id, :tournament, :twitch)
    end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
    require 'open-uri'
    streamers = open("https://api.twitch.tv/kraken/streams?game=DotA%202&limit=8").read
    @streamersJSON = JSON.parse(streamers)
    require 'rss'
    @rssNews = RSS::Parser.parse(open('http://feeds.thescoreesports.com/dota2.rss').read, false).items[0..4]
  end
end

app/controllers/wow_controller.rb
class WowController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_diff(start_time, end_time)
    seconds_diff = (start_time - end_time).to_i.abs

    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    minutes = seconds_diff / 60
    seconds_diff -= minutes * 60

    seconds = seconds_diff

    "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}:#{seconds.to_s.rjust(2, '0')}"
  end

  def get_image(game)
    case game
    when "Dota 2"
      "game/dota-logo.png"
    when "Counterstrike Global Offensive"
      "game/csgo-logo.png"
    when "Overwatch"
      "game/overwatch-logo.png"
    when "World of Warcraft"
      "game/wow-logo.png"
    else
      "game/error-icon.png"
    end
  end
end

app/helpers/csgo_helper.rb
module CsgoHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dota_helper.rb
module DotaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/overwatch_helper.rb
module OverwatchHelper
end

app/helpers/wow_helper.rb
module WowHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team1 %><br>
    <%= f.text_field :team1 %>
  </div>
  <div class="field">
    <%= f.label :team1_score %><br>
    <%= f.text_field :team1_score %>
  </div>
  <div class="field">
    <%= f.label :team2 %><br>
    <%= f.text_field :team2 %>
  </div>
  <div class="field">
    <%= f.label :team2_score %><br>
    <%= f.text_field :team2_score %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :tournament %><br>
    <%= f.text_field :tournament %>
  </div>
  <div class="field">
    <%= f.label :twitch %><br>
    <%= f.text_field :twitch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>

<table>
  <thead>
    <tr>
      <th>Team1</th>
      <th>Team1 score</th>
      <th>Team2</th>
      <th>Team2 score</th>
      <th>Game</th>
      <th>Tournament</th>
      <th>Twitch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.team1 %></td>
        <td><%= match.team1_score %></td>
        <td><%= match.team2 %></td>
        <td><%= match.team2_score %></td>
        <td><%= match.game %></td>
        <td><%= match.tournament %></td>
        <td><%= match.twitch %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team1:</strong>
  <%= @match.team1 %>
</p>

<p>
  <strong>Team1 score:</strong>
  <%= @match.team1_score %>
</p>

<p>
  <strong>Team2:</strong>
  <%= @match.team2 %>
</p>

<p>
  <strong>Team2 score:</strong>
  <%= @match.team2_score %>
</p>

<p>
  <strong>Game:</strong>
  <%= @match.game %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @match.tournament %>
</p>

<p>
  <strong>Twitch:</strong>
  <%= @match.twitch %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>